export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_FILTERED_PRODUCTS = "SET_FILTERED_PRODUCTS";
